name: Build Process Outdated
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      game_repo:
        required: true
        type: string
      game_name:
        required: true
        type: string
      game_branch:
        required: false
        type: string
      game_checkout:
        required: false
        type: string

jobs:
  build-nuclide-sdk-games:
    runs-on: ubuntu-latest
    container:
        image: data.forgejo.org/oci/node:20-bullseye
    timeout-minutes: 120

    steps:
      - name: Install necessary packages
        run: |
          # sudo apt update
          # sudo apt install git make gcc pkg-config -y
          # sudo apt install libpng-dev mesa-common-dev libvulkan-dev  libxtst-dev libxss-dev libxrandr-dev libxcursor-dev libasound2-dev libatopology-dev libjpeg-dev libspeex-dev libspeexdsp-dev libopus-dev libvorbis-dev libsdl2-dev autoconf automake libtool libavformat-dev libswscale-dev -y

      - name: Git Games from repo
        run: |
          # Get Nuclide SDK (official edition)
          git clone https://code.idtech.space/vera/nuclide.git -b Develop nuclide
          cd nuclide
          ## Checkout
          git checkout 07d230983f

          # Get FTEQCC
          mkdir ThirdParty
          git clone https://github.com/fte-team/fteqw.git ThirdParty/fteqw
          ## Checkout
          cd ThirdParty/fteqw
          git checkout 5662b3a
          cd ../../
          ## Build FTEQCC
          make fteqcc

          # Get Games
          git clone https://code.idtech.space/fn/valve.git -b Develop valve
          ## Checkout
          cd valve
          git checkout fcc78e5ad3
          cd ../
          if [[ -f "${{ inputs.game_branch }}" ]]; then
              git clone https://code.idtech.space/"${{ inputs.game_repo }}".git -b "${{ inputs.game_branch }}" "${{ inputs.game_name }}"
              if [[ -f "${{ inputs.game_checkout }}" ]]; then
                cd "${{ inputs.game_name }}"
                git checkout "${{ inputs.game_checkout }}"
                cd ../
              fi
          else
              git clone https://code.idtech.space/"${{ inputs.game_repo }}".git "${{ inputs.game_name }}"
          fi

      - name: Build Games
        run: |
          cd nuclide
          export PATH=$PATH:$GITHUB_WORKSPACE/nuclide/

          # Build and Pack it to .pk*
          # make dist-pak NAME=bin GAME=valve
          make dist-pak NAME=bin GAME="${{ inputs.game_name }}"


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ inputs.game_name }}
          path: |
            nuclide/build/bin-content/${{ inputs.game_name }}/*.pk*
