name: Build Half-Life Opposing Force

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-valve:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-process.yml
    secrets: inherit
    with:
      game_repo: "fn/gearbox"
      game_name: "gearbox"
      game_branch: "Develop"
