name: Build Scientist Hunt

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-scihunt:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-process.yml
    secrets: inherit
    with:
      game_repo: "fn/scihunt"
      game_name: "scihunt"
