name: Build Gunslinger Saga

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-hl2:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-process.yml
    secrets: inherit
    with:
      game_repo: "fn/rewolf"
      game_name: "rewolf"
