name: Build Counter Strike Source

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-css:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-process.yml
    secrets: inherit
    with:
      game_repo: "fn/css"
      game_name: "css"
      game_base: "hl2"
