name: Build Counter-Strike 1.5

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-valve:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-process-outdated.yml
    secrets: inherit
    with:
      game_repo: "fn/cstrike"
      game_name: "cstrike"
      game_branch: "Develop"
      game_checkout: "38fb0a23b5"
