name: Build Half-Life 2

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-hl2:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-process.yml
    secrets: inherit
    with:
      game_repo: "fn/hl2"
      game_name: "hl2"
      game_plugins: "true"
