name: Build Counter-Strike 1.5

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-valve:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-process-outdated.yml
    secrets: inherit
    with:
      game_repo: "fn/valve"
      game_name: "valve"
      game_branch: "Develop"
